rarity_map = {
    1: "💫 Rare",
    2: "🌿 Medium",
    3: "🦄 Legendary",
    4: "💮 Special Edition",
    5: "🔮 Limited Edition",
    6: "🎉 Festival",
    7: "🍂 Seasonal",
    8: "🎐 Celestial", 
    9: "❄️ Winter",
    10: "💝 Valentine",
    11: "🔞 Erotic",
    12: "🪽 AMV",
    13: "🐉 Ethereal",
    14: "🕌 Fast edition",
    15: "🎬 Hollywood",
    16: "🎃 Halloween",
    17: "🌈 Chroma edition",
    18: "⚙🛠️ Customized",
    19: "☔ Rain edition",
    20: "📽️ Webseries",
    21: "🧚‍♂️ kami",
    22: "🍭 Winter event",
    23: "✨ Kinetic Art",
    24: "👑 Royal Pass Edition",
}

RARITY_NAMES = [
    "💫 Rare",
    "🌿 Medium",
    "🦄 Legendary",
    "💮 Special Edition",
    "🔮 Limited Edition",
    "🎉 Festival",
    "🍂 Seasonal",
    "🎐 Celestial", 
    "❄️ Winter",
    "💝 Valentine",
    "🔞 Erotic",
    "🪽 AMV",
    "🐉 Ethereal", 
    "🕌 Fast edition",
    "🎬 Hollywood",
    "🎃 Halloween",
    "🌈 Chroma edition",
    "⚙🛠️ Customized",
    "☔ Rain edition",
    "✨ Kinetic Art",
    "👑 Royal Pass Edition",
]


rarity_map2 = {
     "💫 Rare": "💫",
     "🌿 Medium": "🌿",
     "🦄 Legendary": "🦄",
     "💮 Special Edition": "💮",
     "🔮 Limited Edition": "🔮",
     "🎉 Festival": "🎉",
     "🍂 Seasonal": "🍂",
     "🎐 Celestial": "🎐",
     "❄️ Winter": "❄️",
     "💝 Valentine": "💝",
     "🔞 Erotic": "🔞",
     "🪽 AMV": "🪽",
     "🐉 Ethereal": "🐉",
     "🕌 Fast edition": "🕌",
     "🎬 Hollywood": "🎬",
     "🎃 Halloween": "🎃",
     "🌈 Chroma edition": "🌈",
     "⚙🛠️ Customized": "⚙🛠️",
     "☔ Rain edition": "☔",
     "✨ Kinetic Art": "✨",
     "👑 Royal Pass Edition": "👑",
}

RARITY_R = [
    ("💫 Rare", 1400),
    ("🌿 Medium", 6000),
    ("🦄 Legendary", 8000),
    ("💮 Special Edition", 10000),
    ("🔮 Limited Edition", 24000),
    ("🎉 Festival", 28000),
    ("🍂 Seasonal", 40000),
    ("🎐 Celestial", 50000),
    ("🪽 AMV", 300000),
    ("🕌 Fast edition", 80000),
    ("🎬 Hollywood", 100000),
    ("🎃 Halloween", 30000),
    ("🌈 Chroma edition", 50000),
    ("✨ Kinetic Art", 100000),
]


char_power = {
     "💫 Rare": 100,
     "🌿 Medium": 200,
     "🦄 Legendary": 300,
     "💮 Special Edition": 500,
     "🔮 Limited Edition": 600,
     "🎉 Festival": 700,
     "🍂 Seasonal": 700,
     "🎐 Celestial": 1000,
     "❄️ Winter": 1000,
     "💝 Valentine": 1100,
     "🔞 Erotic": 1700,
     "🪽 AMV": 1900,
     "🐉 Ethereal": 1900,
     "🕌 Fast edition": 100,
     "🎬 Hollywood": 1900,
     "🎃 Halloween": 1600,
     "🌈 Chroma edition": 1100,
     "⚙🛠️ Customized": 2500,
     "☔ Rain edition": 1100,
     "✨ Kinetic Art": 2000,
     "👑 Royal Pass Edition": 2200,
}


bounty_values = {
            '💫 Rare': 100,
            '🌿 Medium': 150,
            '🦄 Legendary': 200,
            '💮 Special Edition': 300,
            '🔮 Limited Edition': 400,
            '🎉 Festival': 500,
            '🍂 Seasonal': 600,
            '🎐 Celestial': 700,
            '❄️ Winter': 800,
            '💝 Valentine': 1000,
            '🔞 Erotic': 650,
            '🪽 AMV': 500,
            '🐉 Ethereal': 450,
            '🕌 Fast edition': 260,
            '🎬 Hollywood': 400,
            '🎃 Halloween': 500,
            '🌈 Chroma edition': 500,
            '☔ Rain edition': 200,
            '✨ Kinetic Art': 500,
            '👑 Royal Pass Edition': 1200,
}

rarity_counts = {
            "💫 Rare": 0,
            "🌿 Medium": 0,
            "🦄 Legendary": 0,
            "💮 Special Edition": 0,
            "🔮 Limited Edition": 0,
            "🎉 Festival": 0,
            "🍂 Seasonal": 0,
            "🎐 Celestial": 0,
            "❄️ Winter": 0,
            "💝 Valentine": 0,
            "🔞 Erotic": 0,
            "🪽 AMV": 0,
            "🐉 Ethereal": 0,
            "🕌 Fast edition": 0,
            "🎬 Hollywood": 0,
            "🎃 Halloween": 0,
            "⚙🛠️ Customized": 0,
            "🌈 Chroma edition": 0,
            "☔ Rain edition": 0,
            "✨ Kinetic Art": 0,
            "👑 Royal Pass Edition": 0,
}


rarity_map3 = {
    "💫 Rare": "💫",
    "🌿 Medium": "🌿",
    "🦄 Legendary": "🦄",
    "💮 Special Edition": "💮",
    "🔮 Limited Edition": "🔮",
    "🎉 Festival": "🎉",
    "🍂 Seasonal": "🍂",
    "🎐 Celestial": "🎐",
    "🪽 AMV": "🪽",
    "🕌 Fast edition": "🕌",
    "🎬 Hollywood": "🎬",
    "🎃 Halloween": "🎃",
    "🌈 Chroma edition": "🌈",
    "✨ Kinetic Art": "✨",
}
